#!/data/data/com.termux/files/usr/bin/bash
#su -c reboot -p
modpes() {
   su -c settings put global airplane_mode_on 1
   su -c am broadcast -a android.intent.action.AIRPLANE_MODE
   su -c settings put global airplane_mode_on 0
   su -c am broadcast -a android.intent.action.AIRPLANE_MODE
}
reboost() {
   su -c am start -S gem.bix.de/.MainActivity
   sleep 1
   su -c input keyevent TAB TAB SPACE
}
sapu() {
  su -c am force-stop vtechnotm.com.deviceid
  su -c am force-stop com.google.android.gms
  su -c am force-stop com.android.vending
  su -c am force-stop com.ocbcnisp.onemobileapp
  su -c am force-stop gem.bix.brow
  su -c am start com.android.launcher3/.shady.ShadyLauncher
  su -c am start com.google.android.apps.nexuslauncher/.NexusLauncherActivity
}
acak() {
  su -c am start -S gem.bix.de/gem.bix.de.MainActivity
  sleep 1.6
  su -c input keyevent TAB TAB TAB SPACE
  su -c input keyevent TAB TAB SPACE DPAD_RIGHT DPAD_RIGHT SPACE
  su -c input keyevent DPAD_LEFT DPAD_LEFT DPAD_LEFT SPACE SPACE SPACE DPAD_RIGHT SPACE
}
modpes
mkdir -p /sdcard/data/xml/ /sdcard/data/BixDE/
su -c cp -p Setting_.eg /sdcard/data/BixDE/
su -c cp /data/data/gem.bix.TeBe/shared_prefs/DataProfilesCache.xml /sdcard/data/xml/
su -c cp /data/data/gem.bix.de/shared_prefs/user_prefs.xml /sdcard/data/xml/

TB=$(xmllint --xpath 'string(//string[@name="currentProfile"])' /sdcard/data/xml/DataProfilesCache.xml)
DEVICEID=$(xmllint --xpath 'string(//boolean[@name="deviceid"]/@value)' /sdcard/data/xml/user_prefs.xml)
ADSVAL=$(xmllint --xpath 'string(//string[@name="adsid_val"])' /sdcard/data/xml/user_prefs.xml)

if [[ $TB == "0 R 1" ]]
then reboost; sapu
elif [[ -f /sdcard/data/xml/user_prefs.xml && $DEVICEID == true && $ADSVAL != "00000000–0000–0000–0000–000000000000" ]]
then reboost; sapu
else acak; sapu
fi
#rm -rf /sdcard/data/xml/
